version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/go:1.21
    steps:
      - checkout
      - run:
          name: Install golangci-lint
          command: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
      - run:
          name: Run golangci-lint
          command: $(go env GOPATH)/bin/golangci-lint run --timeout 5m ./...

  test:
    docker:
      - image: cimg/go:1.21
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.mod" }}
      - run:
          name: Download Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.mod" }}
          paths:
            - "/home/circleci/go/pkg/mod"
      - run:
          name: Run tests with coverage and race detector
          command: go test -v -race -coverprofile=coverage.out ./...

  benchmark:
    docker:
      - image: cimg/go:1.21
    steps:
      - checkout
      - run:
          name: Run benchmarks
          command: go test -run=^$ -bench=. -benchmem ./...

workflows:
  build-test:
    jobs:
      - lint
      - test:
          requires:
            - lint
      - benchmark:
          requires:
            - test
