version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/go:1.21
    steps:
      - checkout
      - run:
          name: Clean modcache
          command: go clean -modcache
      - run:
          name: Check Go env
          command: go env && pwd && ls -la && cat go.mod
      - run:
          name: Install golangci-lint
          command: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.60.3
      - run:
          name: Build all packages
          command: go build -v ./...
      - run:
          name: Run golangci-lint
          command: $(go env GOPATH)/bin/golangci-lint run --timeout 5m ./...

  test:
    docker:
      - image: cimg/go:1.21
    steps:
      - checkout
      - run:
          name: Clean modcache
          command: go clean -modcache
      - run:
          name: Run tests with coverage and race detector
          command: go test -v -race -coverprofile=coverage.out ./...

  benchmark:
    docker:
      - image: cimg/go:1.21
    steps:
      - checkout
      - run:
          name: Run benchmarks
          command: go test -run=^$ -bench=. -benchmem ./...

workflows:
  build-test:
    jobs:
      - lint
      - test:
          requires:
            - lint
      - benchmark:
          requires:
            - test
